### ISSUE TITLE
Error while running maegatk

### ISSUE THREAD

**Issue by NBurnaevskiy** [caleblareau/maegatk#16]
I was trying to run maegatk. It finished splitting bam file and started genotyping, but soon collapsed with the following traceback.

Tue Mar 19 14:22:24 PDT 2024: Genotyping samples with 10 threads
Traceback (most recent call last):
  File "/net/module/sw/maegatk/0.2.0/bin/maegatk", line 10, in <module>
    sys.exit(main())
  File "/net/module/sw/maegatk/0.2.0/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/net/module/sw/maegatk/0.2.0/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/net/module/sw/maegatk/0.2.0/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/net/module/sw/maegatk/0.2.0/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/net/module/sw/maegatk/0.2.0/lib/python3.10/site-packages/maegatk/cli.py", line 300, in main
    yaml.dump(dict1, yaml_file, default_flow_style=False, Dumper=yaml.RoundTripDumper)
  File "/net/module/sw/maegatk/0.2.0/lib/python3.10/site-packages/ruamel/yaml/main.py", line 1251, in dump
    error_deprecation('dump', 'dump', arg="typ='unsafe', pure=True")
  File "/net/module/sw/maegatk/0.2.0/lib/python3.10/site-packages/ruamel/yaml/main.py", line 1039, in error_deprecation
    raise AttributeError(s, name=None)
AttributeError: 
"dump()" has been removed, use

  yaml = YAML(typ='unsafe', pure=True)
  yaml.dump(...)

instead of file "/net/module/sw/maegatk/0.2.0/lib/python3.10/site-packages/maegatk/cli.py", line 300

				yaml.dump(dict1, yaml_file, default_flow_style=False, Dumper=yaml.RoundTripDumper)

Would you have advice?

**Comment by Gregory94** [comment]
Hi @NBurnaevskiy 
I have a similar problem. Did you already find a solution?

**Comment by amyruthvandiver** [comment]
@NBurnaevskiy and @Gregory94, I am getting this same error... did you happen to find a solution?

**Comment by NBurnaevskiy** [comment]
> [@NBurnaevskiy](https://github.com/NBurnaevskiy) and [@Gregory94](https://github.com/Gregory94), I am getting this same error... did you happen to find a solution?

Most likely I did, bit I don't remember how. It was a while ago, sorry.
@Gregory94  sorry, forgot to comment before. I don't remember what was the fix
