### ISSUE TITLE
No output and intermediate file

### ISSUE THREAD

**Issue by CHAOYiming** [caleblareau/maegatk#7]
Dear community, 

Thanks for developing this tool! 
I am applying both mgatk and maegatk on my own MAESTER dataset. 
It goes well with mgatk tenx mode but doesnt give any output from maegatk for more than 20 hours. 
My maegatk commands are as followed: 

> maegatk bcall -i ../outs/possorted_genome_bam.bam -g ../reference/refdata-gex-GRCh38-2020-A/fasta/genome.fa -c 8 -ub UB -bt CB -z

The current out directory contains: 
```
(venv3) (mgatk) [yiming@biomed1 maegatk]$ ls -lR
.:
total 4
drwxrwxr-x 4 yiming yiming  43 Oct 11 21:48 maegatk_out
-rw------- 1 yiming yiming 283 Oct 11 21:48 nohup.out

./maegatk_out:
total 0
drwxrwxr-x 2 yiming yiming 10 Oct 11 21:48 final
drwxrwxr-x 3 yiming yiming 35 Oct 11 21:48 temp

./maegatk_out/final:
total 0

./maegatk_out/temp:
total 0
drwxrwxr-x 2 yiming yiming 10 Oct 11 21:48 barcoded_bams

./maegatk_out/temp/barcoded_bams:
total 0
```
log file: 
```
Tue Oct 11 21:48:02 HKT 2022: maegatk v0.1.1
Tue Oct 11 21:48:02 HKT 2022: Found bam file: /usersdata/yiming/VIO/mito_cellranger/sc-D08/sc-D08/outs/possorted_genome_bam.bam for genotyping.
Tue Oct 11 21:48:02 HKT 2022: Will determine barcodes with at least: 100 mitochondrial reads.
```
I am not sure what's wrong and hope to get some help from you. Thanks!

**Comment by caleblareau** [comment]
My best guess is that the mitochondrial chromosome in the run and what’s in the fasta / bam file are different. I think maegatk assumes chrM and maybe you have MT?

On Oct 12, 2022, at 5:26 AM, Yiming ***@***.******@***.***>> wrote:



Dear community,

Thanks for developing this tool!
I am applying both mgatk and maegatk on my own MAESTER dataset.
It goes well with mgatk tenx mode but doesnt give any output from maegatk for more than 20 hours.
My maegatk commands are as followed:

maegatk bcall -i ../outs/possorted_genome_bam.bam -g ../reference/refdata-gex-GRCh38-2020-A/fasta/genome.fa -c 8 -ub UB -bt CB -z

The current out directory contains:

(venv3) (mgatk) ***@***.*** maegatk]$ ls -lR
.:
total 4
drwxrwxr-x 4 yiming yiming  43 Oct 11 21:48 maegatk_out
-rw------- 1 yiming yiming 283 Oct 11 21:48 nohup.out

./maegatk_out:
total 0
drwxrwxr-x 2 yiming yiming 10 Oct 11 21:48 final
drwxrwxr-x 3 yiming yiming 35 Oct 11 21:48 temp

./maegatk_out/final:
total 0

./maegatk_out/temp:
total 0
drwxrwxr-x 2 yiming yiming 10 Oct 11 21:48 barcoded_bams

./maegatk_out/temp/barcoded_bams:
total 0


log file:

Tue Oct 11 21:48:02 HKT 2022: maegatk v0.1.1
Tue Oct 11 21:48:02 HKT 2022: Found bam file: /usersdata/yiming/VIO/mito_cellranger/sc-D08/sc-D08/outs/possorted_genome_bam.bam for genotyping.
Tue Oct 11 21:48:02 HKT 2022: Will determine barcodes with at least: 100 mitochondrial reads.


I am not sure what's wrong and hope to get some help from you. Thanks!

**Comment by CHAOYiming** [comment]
I double checked the reference genome i m using (cellranger: refdata-gex-GRCh38-2020-A) and the output bam file, both are chrM.

**Comment by CHAOYiming** [comment]
I finally got this message: 
```
Wed Oct 12 17:04:37 HKT 2022: maegatk v0.1.1
Wed Oct 12 17:04:37 HKT 2022: Found bam file: /usersdata/yiming/VIO/mito_cellranger/sc-D08/sc-D08/outs/possorted_genome_bam.bam for genotyping.
Wed Oct 12 17:04:37 HKT 2022: Will determine barcodes with at least: 100 mitochondrial reads.
Traceback (most recent call last):
  File "/home/yiming/venv3/bin/maegatk", line 11, in <module>
    load_entry_point('maegatk==0.1.1', 'console_scripts', 'maegatk')()
  File "/home/yiming/venv3/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/yiming/venv3/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/yiming/venv3/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yiming/venv3/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/yiming/venv3/lib/python3.8/site-packages/maegatk/cli.py", line 123, in main
    fastaf, mito_chr, mito_length = handle_fasta_inference(mito_genome, supported_genomes, script_dir, mode, of)
  File "/home/yiming/venv3/lib/python3.8/site-packages/maegatk/maegatkHelp.py", line 106, in handle_fasta_inference
    fasta = parse_fasta(fastaf) 
  File "/home/yiming/venv3/lib/python3.8/site-packages/maegatk/maegatkHelp.py", line 71, in parse_fasta
    sequences[name] = sequences[name] + line.strip()
MemoryError
```
Anyway thanks! I will realign with STAR and see if could improve.

**Comment by caleblareau** [comment]
It says you are getting a memory error when parsing the fasta file; can you supply the fasta that is only the mitochondrial genome (there are some built in already for hg38)

On Oct 12, 2022, at 10:03 PM, Yiming ***@***.******@***.***>> wrote:



I finally got this message:

Wed Oct 12 17:04:37 HKT 2022: maegatk v0.1.1
Wed Oct 12 17:04:37 HKT 2022: Found bam file: /usersdata/yiming/VIO/mito_cellranger/sc-D08/sc-D08/outs/possorted_genome_bam.bam for genotyping.
Wed Oct 12 17:04:37 HKT 2022: Will determine barcodes with at least: 100 mitochondrial reads.
Traceback (most recent call last):
  File "/home/yiming/venv3/bin/maegatk", line 11, in <module>
    load_entry_point('maegatk==0.1.1', 'console_scripts', 'maegatk')()
  File "/home/yiming/venv3/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/yiming/venv3/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/yiming/venv3/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yiming/venv3/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/yiming/venv3/lib/python3.8/site-packages/maegatk/cli.py", line 123, in main
    fastaf, mito_chr, mito_length = handle_fasta_inference(mito_genome, supported_genomes, script_dir, mode, of)
  File "/home/yiming/venv3/lib/python3.8/site-packages/maegatk/maegatkHelp.py", line 106, in handle_fasta_inference
    fasta = parse_fasta(fastaf)
  File "/home/yiming/venv3/lib/python3.8/site-packages/maegatk/maegatkHelp.py", line 71, in parse_fasta
    sequences[name] = sequences[name] + line.strip()
MemoryError


Anyway thanks! I will realign with STAR and see if could improve.

**Comment by dstyaaaaaa** [comment]
Hi,  I have the same situation of no output and the same output directory to you. But my bam file and reference looks like both MT in terminal, and the log file don't have any error information.  I used Hisat2 to alignment. I don't know whether it is the problem of data or the problem of alignment. I hope I can get some help from you . Many thanks!

```nohup: ignoring input
Wed Sep 13 19:22:37 CST 2023: maegatk v0.1.1
Wed Sep 13 19:22:37 CST 2023: Found bam file: ./output.sorted.bam for genotyping.
Wed Sep 13 19:22:37 CST 2023: Will determine barcodes with at least: 100 mitochondrial reads.
```

my command:

`maegatk bcall -i ./output.sorted.bam -g ../clean/index/***.***.dna.primary_assembly.fa -c 10 -z`

My reference is downloaded at Ensembl.

**Comment by Aggarwal-Ayush** [comment]
Hi @dstyaaaaaa @CHAOYiming 
Were you able to figure out a solution for this?
I'm also stuck at the same place and it says MT in both my bam and genome file.

Thanks
Ayush
